### ISSUE TITLE
请问运行脚本遇到SyntaxError怎么解决呢？

### ISSUE THREAD

**Issue by bin70** [roceys/JD#1]
谢谢您的分享，请问一下运行脚本遇到下面这个问题，要怎么解决呢？是473行报的错误:

`23:01:29.926/E: SyntaxError: invalid object initializer (/storage/emulated/0/脚本/JD1111-2020.js#473)
SyntaxError: invalid object initialize`

运行环境是Android 10

**Comment by pandipper** [comment]
多谢大佬的分享
自动脚本运行到第六或第七次的时候会中止任务，弹出08:54:49.509/E: TypeError: Cannot call method "parent" of null (/storage/emulated/0/脚本/京东.js#1)TypeError: Cannot call method "parent" of null
    at /storage/emulated/0/脚本/京东.js:1:0
    at doTask (/storage/emulated/0/脚本/京东.js:1:0)
    at /storage/emulated/0/脚本/京东.js:1:0

华为机型，
大佬幸苦了

**Comment by roceys** [comment]
已经更新了，再试试哦！

**Comment by bin70** [comment]
谢谢您的回复！已经重新下载最新版本，运行还是在473报错:
![Screenshot_20201026-152444](https://user-images.githubusercontent.com/27135261/97144542-97443280-179f-11eb-8cee-498e51522786.jpg)

我猜想不是您脚本的问题，在运行其他人的repo中下载的脚本也遇到同样的报错，请问是不是和运行环境有关系呢？我的环境是´Android 10´上的´autojs4.1.1-Alpha2´，和您的是否一致呢？

**Comment by roceys** [comment]
你这个下载错了，https://github.com/roceys/JD/blob/master/JD1111-2020.js 下载这个文件（右键另存为），手机上就复制这一行代码，到autojs里新建脚本再粘贴就成。

**Comment by roceys** [comment]
难怪你taobao和jd都用不了，我还纳闷着呢。

**Comment by roceys** [comment]
我到readme里更新一下下载方法了，照顾下网速不好的朋友。

**Comment by bin70** [comment]
谢谢您，已可以正常使用。
