### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by pandipper** [roceys/JD#2]
多谢大佬的分享
自动脚本运行到第六或第七次的时候会中止任务，弹出08:54:49.509/E: TypeError: Cannot call method "parent" of null (/storage/emulated/0/脚本/京东.js#1)TypeError: Cannot call method "parent" of null
at /storage/emulated/0/脚本/京东.js:1:0
at doTask (/storage/emulated/0/脚本/京东.js:1:0)
at /storage/emulated/0/脚本/京东.js:1:0

华为机型，
大佬幸苦了

**Comment by csdjl88** [comment]
> 多谢大佬的分享
> 自动脚本运行到第六或第七次的时候会中止任务，弹出08:54:49.509/E: TypeError: Cannot call method "parent" of null (/storage/emulated/0/脚本/京东.js#1)TypeError: Cannot call method "parent" of null
> at /storage/emulated/0/脚本/京东.js:1:0
> at doTask (/storage/emulated/0/脚本/京东.js:1:0)
> at /storage/emulated/0/脚本/京东.js:1:0
> 
> 华为机型，
> 大佬幸苦了

Vivo也是这个情况

**Comment by roceys** [comment]
> 多谢大佬的分享
> 自动脚本运行到第六或第七次的时候会中止任务，弹出08:54:49.509/E: TypeError: Cannot call method "parent" of null (/storage/emulated/0/脚本/京东.js#1)TypeError: Cannot call method "parent" of null
> at /storage/emulated/0/脚本/京东.js:1:0
> at doTask (/storage/emulated/0/脚本/京东.js:1:0)
> at /storage/emulated/0/脚本/京东.js:1:0
> 
> 华为机型，
> 大佬幸苦了

刚更新了一波再试试，我小米、华为上正常了。

**Comment by pandipper** [comment]
运行正常，多谢大佬
